version: 0.0
os: linux 
runas: root
files:
    - source: / 
      destination: /home/ubuntu/node
      timeout: 300
     
      


hooks:
   
   ApplicationStart:
         - location: /script/start_server.sh
           timeout: 300
           
           
