version: 0.0
os: linux 
runas: root
files:
    - source: / 
      destination: /home/ubuntu/node
      timeout: 300
     
      
   
hooks:
  BeforeInstall:
    - location: script/Install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/start_server.sh
      timeout: 300
      runas: root
      
  ApplicationStop:
    - location: script/stop_service.sh
      timeout: 300
      runas: root
    

           
